OPENAI_API_KEY = "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"

[connections.snowflake]
user = "mundrasn"
password = "pinkSticker45"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "kq80609.ca-central-1.aws"