OPENAI_API_KEY = "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"

[connections.snowflake]
user = "snigdham"
password = "pinkSticker45"
warehouse = "WH_GENAI"
role = "QDA_SI23_DEVELOPER"
account = "pa52620.australia-east.azure"